{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 19:53:52,977+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in on_price_update_date\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 19:53:52,982+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in on_price_update_date\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 19:53:54,896+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in on_price_update_date\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 19:53:55,029+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in on_price_update_date\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 20:49:17,189+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 20:49:17,191+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 20:49:19,114+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 20:49:19,189+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 20:59:50,673+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 20:59:50,678+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 20:59:52,590+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 20:59:52,729+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 21:09:22,463+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 21:09:22,468+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 21:09:24,390+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 21:09:24,518+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"can only concatenate str (not \"dict\") to str","timestamp":"2023-12-01 21:10:35,476+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 46, in onmessage\n    print(\"Last updated price :: \"+ message)\nTypeError: can only concatenate str (not \"dict\") to str","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"can only concatenate str (not \"dict\") to str","timestamp":"2023-12-01 21:10:35,481+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 46, in onmessage\n    print(\"Last updated price :: \"+ message)\nTypeError: can only concatenate str (not \"dict\") to str","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"can only concatenate str (not \"dict\") to str","timestamp":"2023-12-01 21:10:37,451+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 46, in onmessage\n    print(\"Last updated price :: \"+ message)\nTypeError: can only concatenate str (not \"dict\") to str","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"can only concatenate str (not \"dict\") to str","timestamp":"2023-12-01 21:10:37,461+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 46, in onmessage\n    print(\"Last updated price :: \"+ message)\nTypeError: can only concatenate str (not \"dict\") to str","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 21:11:22,017+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 21:11:22,022+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 21:11:23,959+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 21:11:24,012+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[0][\"ltp\"])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"1","timestamp":"2023-12-01 21:13:00,133+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[1]['ltp'])\nKeyError: 1","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"1","timestamp":"2023-12-01 21:13:00,135+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[1]['ltp'])\nKeyError: 1","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"1","timestamp":"2023-12-01 21:13:02,071+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[1]['ltp'])\nKeyError: 1","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"1","timestamp":"2023-12-01 21:13:02,204+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 45, in onmessage\n    ltp = float(message[1]['ltp'])\nKeyError: 1","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 21:17:32,965+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 46, in onmessage\n    ltp = float(message[0]['ltp'])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 21:17:32,971+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 46, in onmessage\n    ltp = float(message[0]['ltp'])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 21:17:34,890+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 46, in onmessage\n    ltp = float(message[0]['ltp'])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"0","timestamp":"2023-12-01 21:17:34,952+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 46, in onmessage\n    ltp = float(message[0]['ltp'])\nKeyError: 0","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'ltp'","timestamp":"2023-12-01 21:19:51,606+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 46, in onmessage\n    ltp = float(message['ltp'][0])\nKeyError: 'ltp'","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'ltp'","timestamp":"2023-12-01 21:19:51,611+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 46, in onmessage\n    ltp = float(message['ltp'][0])\nKeyError: 'ltp'","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'ltp'","timestamp":"2023-12-01 21:19:53,528+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 46, in onmessage\n    ltp = float(message['ltp'][0])\nKeyError: 'ltp'","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'float' object is not subscriptable","timestamp":"2023-12-01 21:19:53,671+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 46, in onmessage\n    ltp = float(message['ltp'][0])\nTypeError: 'float' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'ltp'","timestamp":"2023-12-01 21:23:04,884+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 46, in onmessage\n    ltp = float(message['ltp'])\nKeyError: 'ltp'","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'ltp'","timestamp":"2023-12-01 21:23:04,887+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 46, in onmessage\n    ltp = float(message['ltp'])\nKeyError: 'ltp'","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"'ltp'","timestamp":"2023-12-01 21:23:06,793+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 46, in onmessage\n    ltp = float(message['ltp'])\nKeyError: 'ltp'","exception_name":"KeyError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"float() argument must be a string or a real number, not 'UtilityOrder'","timestamp":"2023-12-02 01:38:40,096+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 62, in onmessage\n    trade = utility.prepare_buy_trade_input(ltp, option_symbol, \"PE\",1,\"\")\n  File \"C:\\Python_Projects\\fyers\\utility.py\", line 4, in prepare_buy_trade_input\n    round_to_strike = int(round(float(ltp), -2))\nTypeError: float() argument must be a string or a real number, not 'UtilityOrder'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"float() argument must be a string or a real number, not 'UtilityOrder'","timestamp":"2023-12-02 01:38:40,102+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 62, in onmessage\n    trade = utility.prepare_buy_trade_input(ltp, option_symbol, \"PE\",1,\"\")\n  File \"C:\\Python_Projects\\fyers\\utility.py\", line 4, in prepare_buy_trade_input\n    round_to_strike = int(round(float(ltp), -2))\nTypeError: float() argument must be a string or a real number, not 'UtilityOrder'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"float() argument must be a string or a real number, not 'UtilityOrder'","timestamp":"2023-12-02 01:38:41,989+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 62, in onmessage\n    trade = utility.prepare_buy_trade_input(ltp, option_symbol, \"PE\",1,\"\")\n  File \"C:\\Python_Projects\\fyers\\utility.py\", line 4, in prepare_buy_trade_input\n    round_to_strike = int(round(float(ltp), -2))\nTypeError: float() argument must be a string or a real number, not 'UtilityOrder'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"float() argument must be a string or a real number, not 'UtilityOrder'","timestamp":"2023-12-02 01:38:42,118+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 52, in onmessage\n    trade = utility.prepare_buy_trade_input(ltp,option_symbol,\"CE\",1,\"\")\n  File \"C:\\Python_Projects\\fyers\\utility.py\", line 4, in prepare_buy_trade_input\n    round_to_strike = int(round(float(ltp), -2))\nTypeError: float() argument must be a string or a real number, not 'UtilityOrder'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"float() argument must be a string or a real number, not 'UtilityOrder'","timestamp":"2023-12-02 01:41:05,471+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 62, in onmessage\n    trade = utility.prepare_buy_trade_input(ltp, option_symbol, \"PE\",1,25)\n  File \"C:\\Python_Projects\\fyers\\utility.py\", line 4, in prepare_buy_trade_input\n    round_to_strike = int(round(float(ltp), -2))\nTypeError: float() argument must be a string or a real number, not 'UtilityOrder'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"float() argument must be a string or a real number, not 'UtilityOrder'","timestamp":"2023-12-02 01:41:05,474+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 62, in onmessage\n    trade = utility.prepare_buy_trade_input(ltp, option_symbol, \"PE\",1,25)\n  File \"C:\\Python_Projects\\fyers\\utility.py\", line 4, in prepare_buy_trade_input\n    round_to_strike = int(round(float(ltp), -2))\nTypeError: float() argument must be a string or a real number, not 'UtilityOrder'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"float() argument must be a string or a real number, not 'UtilityOrder'","timestamp":"2023-12-02 01:41:07,394+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 62, in onmessage\n    trade = utility.prepare_buy_trade_input(ltp, option_symbol, \"PE\",1,25)\n  File \"C:\\Python_Projects\\fyers\\utility.py\", line 4, in prepare_buy_trade_input\n    round_to_strike = int(round(float(ltp), -2))\nTypeError: float() argument must be a string or a real number, not 'UtilityOrder'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"float() argument must be a string or a real number, not 'UtilityOrder'","timestamp":"2023-12-02 01:41:07,544+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 52, in onmessage\n    trade = utility.prepare_buy_trade_input(ltp,option_symbol,\"CE\",1,25)\n  File \"C:\\Python_Projects\\fyers\\utility.py\", line 4, in prepare_buy_trade_input\n    round_to_strike = int(round(float(ltp), -2))\nTypeError: float() argument must be a string or a real number, not 'UtilityOrder'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"UtilityOrder.prepare_buy_trade_input() missing 1 required positional argument: 'qty'","timestamp":"2023-12-02 01:42:15,825+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 61, in onmessage\n    trade = UtilityOrder.prepare_buy_trade_input(ltp, option_symbol, \"PE\",1,25)\nTypeError: UtilityOrder.prepare_buy_trade_input() missing 1 required positional argument: 'qty'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"UtilityOrder.prepare_buy_trade_input() missing 1 required positional argument: 'qty'","timestamp":"2023-12-02 01:42:15,830+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 61, in onmessage\n    trade = UtilityOrder.prepare_buy_trade_input(ltp, option_symbol, \"PE\",1,25)\nTypeError: UtilityOrder.prepare_buy_trade_input() missing 1 required positional argument: 'qty'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"UtilityOrder.prepare_buy_trade_input() missing 1 required positional argument: 'qty'","timestamp":"2023-12-02 01:42:17,762+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 61, in onmessage\n    trade = UtilityOrder.prepare_buy_trade_input(ltp, option_symbol, \"PE\",1,25)\nTypeError: UtilityOrder.prepare_buy_trade_input() missing 1 required positional argument: 'qty'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"UtilityOrder.prepare_buy_trade_input() missing 1 required positional argument: 'qty'","timestamp":"2023-12-02 01:42:17,864+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 51, in onmessage\n    trade = UtilityOrder.prepare_buy_trade_input(ltp,option_symbol,\"CE\",1,25)\nTypeError: UtilityOrder.prepare_buy_trade_input() missing 1 required positional argument: 'qty'","exception_name":"TypeError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"local variable 'ltp' referenced before assignment","timestamp":"2023-12-02 02:26:07,430+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 43, in onmessage\n    if ltp>high_price and not is_break_hig:\nUnboundLocalError: local variable 'ltp' referenced before assignment","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"local variable 'ltp' referenced before assignment","timestamp":"2023-12-02 02:26:07,434+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 43, in onmessage\n    if ltp>high_price and not is_break_hig:\nUnboundLocalError: local variable 'ltp' referenced before assignment","exception_name":"UnboundLocalError"}
{"level":"ERROR","location":"[exception:108] fyers_logger","message":"local variable 'ltp' referenced before assignment","timestamp":"2023-12-02 02:26:09,331+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"C:\\Users\\lenovo\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1418, in On_message\n    self.OnMessage(message)\n  File \"C:\\Python_Projects\\fyers\\15Min-Breakout.py\", line 43, in onmessage\n    if ltp>high_price and not is_break_hig:\nUnboundLocalError: local variable 'ltp' referenced before assignment","exception_name":"UnboundLocalError"}
